spring:
   datasource:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&connectTimeout=3000&socketTimeout=1000&serverTimezone=GMT&useSSL=false
      username: root
      password: 111
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      minIdle: 5
      maxActive: 100
      initialSize: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 50
      removeAbandoned: true
      filters: stat # ,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
      druidLoginName: wjf # 登录druid的账号
      druidPassword: wjf # 登录druid的密码
      cachePrepStmts: true  # 开启二级缓存
      #配置sentinel的地址即可,因为sentinel是监视所有redis节点的,springboot就可以通过sentinel访问到其他redis节点
   redis:
      sentinel:
         master: mymaster
         nodes: 192.168.245.5:26000
#redis集群的连接方式,
#导入包,定义redistemplate,用下面的连接,其他跟普通用法相同
#   redis:
#          timeout: 6000ms
#          password:
#      #       host: 172.16.244.144
#      #       port: 6379
#          cluster:
#            max-redirects: 3  # 获取失败 最大重定向次数 
#            nodes: 172.16.244.144:7000,172.16.244.144:7001,172.16.244.144:7002,172.16.244.144:7003,172.16.244.144:7004,172.16.244.144:7005 
#          lettuce:
#            pool:
#              max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
#              max-idle: 10 # 连接池中的最大空闲连接
#              min-idle: 5 # 连接池中的最小空闲连接
#              max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制
mybatis:
   typeAliasesPackage: com.sxfdu.redis.mapper
   mapperLocations: classpath:/com/sxfdu/redis/mapper/*.xml
   mapperScanPackage: com.sxfdu.redis.mapper
   configLocation: classpath:/mybatis-config.xml